# Generated by Django 5.0.1 on 2024-01-30 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Alugueis', '0002_alter_inquilino_data_vencimento'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagamentosJaneiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agua_pago', models.BooleanField(default=False)),
                ('energia_pago', models.BooleanField(default=False)),
                ('aluguel_pago', models.BooleanField(default=False)),
                ('talao_energia', models.FileField(blank=True, default='', upload_to='janeiro/')),
                ('talao_agua', models.FileField(blank=True, default='', upload_to='janeiro/')),
                ('carne', models.FileField(blank=True, default='', upload_to='janeiro/')),
                ('inquilino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Alugueis.inquilino')),
            ],
            options={
                'verbose_name': 'Pagamento de Janeiro',
                'verbose_name_plural': 'Pagamentos de Janeiro',
            },
        ),
    ]
