# Generated by Django 5.0.1 on 2024-01-30 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pagamentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamentosjaneiro',
            name='agua_pago',
            field=models.BooleanField(default=False, verbose_name='MARQUE SE A CONTA DE ÁGUA FOI PAGA'),
        ),
        migrations.AlterField(
            model_name='pagamentosjaneiro',
            name='aluguel_pago',
            field=models.BooleanField(default=False, verbose_name='MARQUE SE O ALUGUEL FOI PAGO'),
        ),
        migrations.AlterField(
            model_name='pagamentosjaneiro',
            name='carne',
            field=models.FileField(blank=True, default='', upload_to='janeiro/', verbose_name=' ANEXAR CARNÊ PAGO'),
        ),
        migrations.AlterField(
            model_name='pagamentosjaneiro',
            name='energia_pago',
            field=models.BooleanField(default=False, verbose_name='MARQUE SE A CONTA DE ENERGIA FOI PAGA'),
        ),
        migrations.AlterField(
            model_name='pagamentosjaneiro',
            name='talao_agua',
            field=models.FileField(blank=True, default='', upload_to='janeiro/', verbose_name=' ANEXAR TALÃO DE ÁGUA PAGO'),
        ),
        migrations.AlterField(
            model_name='pagamentosjaneiro',
            name='talao_energia',
            field=models.FileField(blank=True, default='', upload_to='janeiro/', verbose_name=' ANEXAR TALÃO DE ENERGIA PAGO'),
        ),
    ]
