# Generated by Django 5.0.1 on 2024-01-30 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alugueis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquilino',
            name='data_vencimento',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
